# Generated by Django 5.2.11 on 2026-02-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='odometer_reading',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
