# Generated by Django 5.2.11 on 2026-02-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_liters_expense_odometer_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='liters',
            new_name='fuel_liters',
        ),
    ]
